# Generated by Django 5.0.6 on 2024-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('loan_amount', models.CharField(max_length=225)),
                ('loan_status', models.CharField(max_length=225)),
            ],
        ),
    ]
